version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
    time: "04:00"
  open-pull-requests-limit: 15
  ignore:
  - dependency-name: react-hook-form
    versions:
    - ">= 4.a"
    - "< 5"
  - dependency-name: react-hook-form
    versions:
    - ">= 5.a"
    - "< 6"
  - dependency-name: react-hook-form
    versions:
    - ">= 6.a"
    - "< 7"
  - dependency-name: react-scripts
    versions:
    - ">= 4.a"
    - "< 5"
  - dependency-name: "@sentry/browser"
    versions:
    - ">= 6.a"
    - "< 7"
  - dependency-name: "@testing-library/react"
    versions:
    - ">= 10.a"
    - "< 11"
  - dependency-name: "@testing-library/react"
    versions:
    - ">= 11.a"
    - "< 12"
  - dependency-name: use-resize-observer
    versions:
    - ">= 7.a"
    - "< 8"
